### ISSUE TITLE
Separation of reflected attributes and attributes with complex keys

### ISSUE THREAD

**Issue by cornerman** [raquo/scala-dom-types#46]
When using the `ComplexHtmlKeys` trait, we mix reflected attributes and attributes into one trait. For consuming libraries, it is not possible to use `ComplexHtmlKeys` and still maintain a separated API for reflected attributes and normal attributes.

Can we fix this by separating the attributes into more traits? Is this desired or do we need a different solution for catering the many different use-cases?

**Comment by raquo** [comment]
Thanks for bringing this up. I'm not going to repeat everything we've chatted about privately, just a quick summary:

- Using CanonicalComplexHtmlKeys trait requires Outwatch to change its published DSL as described in https://github.com/OutWatch/outwatch/pull/235
- We're not sure if it's a big deal or not because the old DSL imports seem needlessly specific
- At the same time we're not fans of SDT causing changes in downstream libraries, the goal of the library is to be flexible
- There is an easy workaround – just don't use that one trait, but it's lame. It shouldn't come to this.
- I'm ok to split the trait in two, but I'm concerned with the growing number of traits that are usually all mixed into a single object. I'm not sure how an object extending 20 traits is represented in JS by Scala.js – does accessing a field for Nth mixed in trait require N lookups in the prototype chain? Does that affect performance much? It's gotta be one of the hottest paths in a web application built on SDT so we do need to pay attention to this.

I can make a fix, but I'm desperately short on time this month, so it might not be a long term fix because I would need to do some performance research to know what that would be. Knowing the following would help me make the right call right now:
- How much do you care about the old Outwatch DSL that is now incompatible? Would you still keep it if I make the change allowing that?
- How soon do you need/want to start using SDT v0.9+?

^ @cornerman

**Comment by cornerman** [comment]
@raquo Thanks for summing this up!

> How much do you care about the old Outwatch DSL that is now incompatible? Would you still keep it if I make the change allowing that?

We might keep it, if we hear that users want this kind of fine-grained import system. But from my perspective, outwatch does not need it and it should be fine without it.

> How soon do you need/want to start using SDT v0.9+?

As soon as possible, which is why I am fine with removing this conflicting bit :)

I agree with you about the performance consideration. This issue is not high-priority, but we should maybe keep it open to see what we can do about the separation into different traits and how it reflects on performance.

**Comment by cornerman** [comment]
We just merged updating to the new SDT version: https://github.com/OutWatch/outwatch/pull/235 :)

**Comment by raquo** [comment]
Ok then, I'll definitely keep this issue open. If anyone else wants to weigh in, please do.

**Comment by raquo** [comment]
Seems like the current design have been working fine enough...
