### ISSUE TITLE
implicit def eventPropToEventPropTransformation interferes sometimes

### ISSUE THREAD

**Issue by doofin** [raquo/scala-dom-types#58]
for example,it will make `elem.events(onClick)` unusable due to that `  def events ` is overloaded with both EventProp and EventPropTransformation.

**Comment by raquo** [comment]
Hey @doofin, you're describing an issue with Laminar, but you filed this in scala-dom-types.

So I'm gonna close this issue here, but please file it again in https://github.com/raquo/Laminar/ and include the specific code that doesn't compile, along with the versions of Scala and Laminar that it happens with for you. I haven't seen this problem before, and looking at the code I can't see the overload causing this. But maybe I'm wrong, which is why I need a way to reproduce this.

**Comment by doofin** [comment]
Sorry ! I will move this issue later
